### ISSUE TITLE
Replay the policy?

### ISSUE THREAD

**Issue by hai-h-nguyen** [maximilianigl/DVRL#3]
Is there any way that we can replay the learned policy from a saved one?

**Comment by maximilianigl** [comment]
Hey, unfortunately not in the codebase. I did have a script that allowed loading a model and running it, but the script was overly complicated because i) It was tied in with our internal db system and ii) it actually allowed "rewinding" back and forth so I didn't add it here. 

If you want I can send it to you, though it's not gonna work out of the box.

**Comment by hai-h-nguyen** [comment]
Thank you but I can do it I believe. Btw, why you use a GRUcell for the baseline RNNpolicy but not the normal GRU network?

**Comment by maximilianigl** [comment]
I don't really remember, but I think there's no particular reason. It's likely because the RL code-base that I started from implemented it this way, whereas, for the particle filter, I was re-using the code from the AESMC paper.
But it shouldn't make a difference, right?

**Comment by hai-h-nguyen** [comment]
Yeah, it seems that the performance is unaffected. Thanks a lot.

**Comment by hai-h-nguyen** [comment]
Hello, what is the command to reproduce the results for MountainHike? I was unable to do that with this command "python ./code/main.py -p with environment.config_file=mountainHike.yaml algorithm.use_particle_filter=False algorithm.model.h_dim=256 algorithm.multiplier_backprop_length=10  opt.lr=1.0e-04 rl_setting.num_processes=16 seed=0 loss_function.encoding_loss_coef=0.0 algorithm.model.obs_loss_coef=0.0" (for RNN policy)>

**Comment by maximilianigl** [comment]
I have to see where I have those old runs. How is it different? Have you tried multiple different seeds?

**Comment by hai-h-nguyen** [comment]
I tried only one seed actually. But it did not learn anything even after 25M steps. The return actually decreased over time. 
![Result](https://user-images.githubusercontent.com/32955308/97894136-27362f00-1d00-11eb-9f06-4f87c0daa1a1.png)

**Comment by maximilianigl** [comment]
Hey, yeah, it definitely shouldn't decrease. I checked my old runs and it seems the only difference is that I didn't change the  multiplier_backprop_length from the default 5. Although I'm not sure why that should change the results so massively. 
But it's weird that it doesn't learn at all... the environment shouldn't be that difficult to learn on.
